spring.application.name=BidSafe
spring.datasource.url=jdbc:mysql://localhost:3306/bid_safe
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.root=INFO
logging.level.bid.safe.lumio.BidSafe=INFO
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
