spring.config.import=optional:file:./.env[.properties]

spring.application.name=BidSafe
server.port=${SERVER_PORT:8080}

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:bid_safe}
spring.datasource.username=${DB_USERNAME:bid_app}
spring.datasource.password=${DB_PASSWORD:bid_app_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

jwt.secret=${JWT_SECRET:change-me-to-a-long-random-secret-at-least-32-chars}

logging.level.root=INFO
logging.level.bid.safe.lumio.BidSafe=INFO
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
