services:

  prometheus:
    image: prom/prometheus:latest
    container_name: bidsafe-prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - monitoring

    restart: unless-stopped


  grafana:
    image: grafana/grafana:latest
    container_name: bidsafe-grafana

    ports:
      - "3000:3000"

    volumes:
      - grafana-data:/var/lib/grafana

    networks:
      - monitoring

    restart: unless-stopped


volumes:
  grafana-data:


networks:
  monitoring:
    driver: bridge